import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { Flex } from "@chakra-ui/react";
import Timeline from "../components/Timeline";
import Navbar from "../components/Navbar";
import "focus-visible/dist/focus-visible";
import Footer from "../components/Footer";
import { Spinner } from "@chakra-ui/react";

export default function Home({ posts }) {
  return (
    <Flex>
      <Head>
        <title>Spacestagram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/shopify.png' />
      </Head>
      <Flex flexDir='column' align='center' w='100%'>
        <Timeline posts={posts} />
        <Navbar />
        <Footer></Footer>
      </Flex>
    </Flex>
  );
}

// Make API calls and pre-render the page at build-time
export async function getServerSideProps() {
  try {
    const link = "https://api.nasa.gov/planetary/apod";
    const res = await fetch(
      link + "?start_date=2021-12-30&thumbs=True&api_key=" + process.env.API_KEY
    );
    const posts = await res.json();
    return {
      props: { posts },
    };
  } catch (error) {
    return { props: {} };
  }
}
