import Head from "next/head";
import { Flex, Heading, Stack, Text } from "@chakra-ui/react";
import Timeline from "../components/Timeline";

export default function Home({ posts }) {
  return (
    <Flex>
      <Head>
        <title>Spacestagram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Timeline posts={posts} />
    </Flex>
  );
}

// Make API calls and pre-render the page at build-time
export async function getServerSideProps() {
  try {
    const link = "https://api.nasa.gov/planetary/apod";
    const res = await fetch(
      link + "?start_date=2021-12-30&thumbs=True&api_key=" + process.env.API_KEY
    );
    const posts = await res.json();
    return {
      props: { posts },
    };
  } catch (error) {
    res.statusCode = 404;
    return { props: {} };
  }
}
